language: node_js,
node_js:  
  - v10.16.3,
cache: npm
local_directory: build
install:
  - npm_ci
script: 
  - npm test
  - npm run build

  deploy:
    provider: pages
    skip-cleanup: true,
    github-token: $GITHUB_TOKEN,
    on:
      branch: develop
