language: node_js
node_js:
  - "stable"
install:
  - npm install
services:
  - postgresql
env:
  - NODE_ENV = test
before_script:
  - psql -c 'CREATE DATABASE testing_test;' -U postgres
  - chmod 0777 ./node_modules/.bin/mocha
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run test
cache:
  directories:
  - "node_modules"
after_success:
  - npm run coveralls
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notification:
  - email: false
