language: node_js
node_js:
  - "stable"
install:
  - npm install
services:
  - postgresql
env:
  - NODE_ENV = test
before_script:
<<<<<<< HEAD
  - psql -c 'CREATE DATABASE testing_test' -U postgres
=======
  - psql -c 'CREATE DATABASE ebewytaa;' -U postgres
>>>>>>> e80387d034197b521e714e6aec8bb60725d46af8
  - chmod 0777 ./node_modules/.bin/mocha
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run test
cache:
  directories:
  - "node_modules"
after_success:
  - npm run coveralls 
  - "node_modules"
install:
  - npm ci
    services:
  - postgresql
  - 
  - npm ci
services:

# before_install:
#   - nvm install
# install:
#   - npm ci
# services:
  - postgresql
env:
  global:
  - NODE_ENV=test
before_script:                         # Install node version from .nvmrc
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notification:
  - email: false
